# Generated by Django 4.2.5 on 2024-02-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_image', models.ImageField(default='teacher/teacher_image_DIR/default.jpg', upload_to='student/student_image_DIR/')),
                ('teacher_age', models.DateField()),
                ('teacher_sex', models.CharField(default='O', max_length=1)),
                ('teacher_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
