# Generated by Django 4.2.5 on 2024-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_image', models.ImageField(default='student/student_image_DIR/default.jpg', upload_to='student/student_image_DIR/')),
                ('student_age', models.DateField()),
                ('student_sex', models.CharField(default='O', max_length=1)),
            ],
        ),
    ]
